export class ViewCounter {
  constructor(ctx) { this.ctx = ctx; }
  async fetch(request) {
    const url = new URL(request.url); const nowKst = new Date(Date.now() + 9*60*60*1000); const kstDate=nowKst.toISOString().slice(0,10);
    if(url.searchParams.get('mode')==='stats'){const yesterdayDate=new Date(nowKst.getTime()-86400000).toISOString().slice(0,10);const today=(await this.ctx.storage.get(`day:${kstDate}`))||0;const yesterday=(await this.ctx.storage.get(`day:${yesterdayDate}`))||0;const days=await this.ctx.storage.list({prefix:'day:'});let total=0;for(const value of days.values())total+=Number(value||0);return Response.json({today,yesterday,total,date:kstDate},{headers:{'Cache-Control':'no-store'}})}
    const key=`day:${kstDate}`,current=(await this.ctx.storage.get(key))||0,next=current+1;await this.ctx.storage.put(key,next);return Response.json({today:next,date:kstDate},{headers:{'Cache-Control':'no-store'}});
  }
}
const HOME_SITES=new Map([['/','barotool'],['/marketing','marketing'],['/marketing/','marketing'],['/qr','qr'],['/qr/','qr'],['/iconmaker','iconmaker'],['/iconmaker/','iconmaker'],['/watermark','watermark'],['/watermark/','watermark'],['/doclab','doclab'],['/doclab/','doclab'],['/couponsem','couponsem'],['/couponsem/','couponsem'],['/unitlab','unitlab'],['/unitlab/','unitlab'],['/stocksem','stocksem'],['/stocksem/','stocksem'],['/quote-workshop','quote-workshop'],['/quote-workshop/','quote-workshop'],['/petcost','petcost'],['/petcost/','petcost'],['/roundsem','roundsem'],['/roundsem/','roundsem'],['/rentalsem','rentalsem'],['/rentalsem/','rentalsem'],['/carvaluelab','carvaluelab'],['/carvaluelab/','carvaluelab'],['/weddingsem','weddingsem'],['/weddingsem/','weddingsem'],['/tutorsem','tutorsem'],['/tutorsem/','tutorsem'],['/areafit','areafit'],['/areafit/','areafit'],['/floorfit','floorfit'],['/floorfit/','floorfit'],['/moldingfit','moldingfit'],['/moldingfit/','moldingfit'],['/packfit','packfit'],['/packfit/','packfit'],['/tilefit','tilefit'],['/tilefit/','tilefit'],['/powercost','powercost'],['/powercost/','powercost'],['/curtainfit','curtainfit'],['/curtainfit/','curtainfit'],['/paintfit','paintfit'],['/paintfit/','paintfit'],['/wallfit','wallfit'],['/wallfit/','wallfit'],['/printfit','printfit'],['/printfit/','printfit'],['/tvfit','tvfit'],['/tvfit/','tvfit'],['/filmfit','filmfit'],['/filmfit/','filmfit'],['/monitorfit','monitorfit'],['/monitorfit/','monitorfit'],['/aircleanfit','aircleanfit'],['/aircleanfit/','aircleanfit'],['/washcleanfit','washcleanfit'],['/washcleanfit/','washcleanfit'],['/moveincleanfit','moveincleanfit'],['/moveincleanfit/','moveincleanfit']]);
class ViewBadgeInjector{constructor(site){this.site=site}element(element){const site=this.site;element.append(`<div id="daily-view-badge" aria-live="polite" style="position:fixed;right:14px;bottom:14px;z-index:9999;padding:8px 11px;border-radius:999px;background:rgba(20,24,32,.88);color:#fff;font:600 12px/1.2 system-ui;box-shadow:0 4px 16px rgba(0,0,0,.18)">오늘 조회수 <span id="daily-view-count">…</span></div><script>(()=>{const n=document.getElementById('daily-view-count');fetch('/api/view?site=${site}',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>n.textContent=Number(d.today||0).toLocaleString('ko-KR')).catch(()=>{const b=document.getElementById('daily-view-badge');if(b)b.style.display='none'})})()</script>`,{html:true})}}
class QuoteWorkshopCrossLinkInjector{element(element){element.append('<aside style="max-width:1040px;margin:18px auto 90px;padding:0 24px"><div style="background:#fff;border:1px solid #e5dfd4;border-radius:18px;padding:20px;line-height:1.7"><b>이사 때 놓치기 쉬운 비용</b><br><a href="/quote-workshop/aircon-relocation-quote-compare.html" style="color:#7b3e20;font-weight:800">에어컨 이전설치 3사 견적 비교 →</a><span style="color:#746e65;font-size:14px"> 기본비뿐 아니라 배관 연장·냉매·앵글·고소작업 추가비까지 비교합니다.</span><br><br><b>입주 시공 비용</b><br><a href="/quote-workshop/balcony-elastic-coating-cost.html" style="color:#7b3e20;font-weight:800">2026 베란다 탄성코트 비용·견적 비교 →</a><br><br><b>결혼 준비 비용</b><br><a href="/weddingsem/" style="color:#7b3e20;font-weight:800">웨딩셈 결혼식 비용 계산기 →</a></div></aside>',{html:true})}}
class RootCrossLinkInjector{element(element){element.append('<aside style="max-width:1120px;margin:0 auto 70px;padding:0 24px"><div style="background:#fff7f5;border:1px solid #eaded9;border-radius:18px;padding:20px;line-height:1.7"><b>무료 비용·견적 도구</b><br><a href="/moveincleanfit/" style="color:#7a4141;font-weight:800">입주·이사청소 견적 3곳 비교 →</a><span style="color:#6f6260;font-size:14px"> 평당가뿐 아니라 포함 범위·추가금·검수 조건까지 비교합니다.</span><br><a href="/washcleanfit/" style="color:#7a4141;font-weight:800">세탁기 청소 견적 3곳 비교 →</a><br><a href="/aircleanfit/" style="color:#7a4141;font-weight:800">에어컨 청소 견적 3곳 비교 →</a><br><a href="/quote-workshop/aircon-relocation-quote-compare.html" style="color:#7a4141;font-weight:800">에어컨 이전설치 3사 견적 비교 →</a><br><a href="/weddingsem/" style="color:#7a4141;font-weight:800">웨딩셈 결혼식 비용 계산기 →</a></div></aside>',{html:true})}}
class QrCrossLinkInjector{element(element){element.append('<aside style="max-width:1120px;margin:0 auto 70px;padding:0 24px"><div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:18px;padding:20px"><a href="/qr/wifi-qr-print.html" style="color:#1d4ed8;font-weight:800">와이파이 QR + 인쇄 안내문 만들기 →</a></div></aside>',{html:true})}}
class MarketingToolUiInjector{element(element){element.append('<script src="/marketing/tool-ui.js"></script>',{html:true})}}
const MARKETING_NON_TOOLS=new Set(['/marketing/','/marketing/index.html','/marketing/about.html','/marketing/privacy.html','/marketing/contact.html']);
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/view'||url.pathname==='/api/view-stats'){const site=(url.searchParams.get('site')||'barotool').toLowerCase();if(!/^[a-z0-9-]{1,40}$/.test(site))return new Response('Bad Request',{status:400});const id=env.VIEW_COUNTER.idFromName(site),stub=env.VIEW_COUNTER.get(id);if(url.pathname==='/api/view-stats'){const u=new URL(request.url);u.pathname='/api/view';u.searchParams.set('mode','stats');return stub.fetch(u.toString())}return stub.fetch(request)}const response=await env.ASSETS.fetch(request),site=HOME_SITES.get(url.pathname),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const marketingTool=url.pathname.startsWith('/marketing/')&&url.pathname.endsWith('.html')&&!MARKETING_NON_TOOLS.has(url.pathname);if(!site&&!marketingTool)return response;let rewriter=new HTMLRewriter();if(site)rewriter=rewriter.on('body',new ViewBadgeInjector(site));if(url.pathname==='/')rewriter=rewriter.on('body',new RootCrossLinkInjector());if(url.pathname==='/quote-workshop'||url.pathname==='/quote-workshop/')rewriter=rewriter.on('body',new QuoteWorkshopCrossLinkInjector());if(url.pathname==='/qr'||url.pathname==='/qr/')rewriter=rewriter.on('body',new QrCrossLinkInjector());if(marketingTool)rewriter=rewriter.on('body',new MarketingToolUiInjector());return rewriter.transform(response)}};